version: "3"
services:
  h2:
    container_name: h2
    image: oscarfonts/h2:latest
    restart: always
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
  spring:
    container_name: spring
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: moonsungkim/docker-practice
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/demo
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - h2